---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-fs-ui
  name: pttg-fs-ui
spec:
  clusterIP: 10.200.147.219
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: pttg-fs-ui
