---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pttg-fs-ui
  namespace: {{.KUBE_NAMESPACE}}
spec:
  podSelector:
    matchLabels:
      name: pttg-fs-ui
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-external